# Garante que o banco seja recriado com nossas tabelas sempre que o projeto rodar
quarkus.hibernate-orm.database.generation=drop-and-create

# Mostra no terminal os comandos SQL reais que o Hibernate está executando
quarkus.hibernate-orm.log.sql=true